language: node_js
node_js:
  "6.2.0"
notifications:
  slack: yoyodesign:4HjysiaAvCJPeibgAYAFssht
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  repo: yoyodesign/gort-docs
  target_branch: master
  on:
    branch: master